apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: web
  labels: # Метки в формате key: value
    app: web
spec: # Описание Pod
  containers: # Описание контейнеров внутри Pod
    - name: app
      image: devopstank/nginx-base-app:1.1
      readinessProbe:
        httpGet:
          path: /index.html
          port: 8080
      livenessProbe:
        tcpSocket: { port: 8000}
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}
  initContainers:
    - name: init-box
      image: busybox
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: app
          mountPath: /app

